# Copyright 2022 Clivern
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Remove latest release
  file:
    path: /srv/app/releases/{{ app_version }}
    state: absent
  tags: [ oxygen, helium ]

- name: Clone project code
  git:
    repo: "{{ git_repo }}"
    dest: /srv/app/releases/{{ app_version }}
    version: "{{ app_version }}"
    accept_hostkey: true
  tags: [ oxygen, helium ]

- name: Ensure cache directory exists
  file:
    path: /srv/app/releases/{{ app_version }}/var/cache
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'
    state: directory
  tags: [ oxygen, helium ]

- name: Create .env config file
  template:
    src: env.j2
    dest: /srv/app/releases/{{ app_version }}/.env
    mode: '0755'
  tags: [ oxygen, helium ]

- name: Update current release symlink
  file:
    src: /srv/app/releases/{{ app_version }}
    dest: /srv/app/current
    state: link
  notify: restart nginx
  tags: [ oxygen, helium ]

- name: Remove current release logs
  file:
    path: /srv/app/releases/{{ app_version }}/var/log
    state: absent
  tags: [ oxygen, helium ]

- name: Update logs symlink
  file:
    src: /srv/app/shared/log
    dest: /srv/app/releases/{{ app_version }}/var/log
    state: link
  tags: [ oxygen, helium ]

- name: Update release owner and permissions
  file:
    dest: /srv/app/releases/{{ app_version }}
    owner: "{{ app_user }}"
    group: "www-data"
    mode: "0755"
    recurse: yes
  tags: [ oxygen, helium ]

- name: Update current release owner and permissions
  file:
    dest: /srv/app/current
    owner: "{{ app_user }}"
    group: "www-data"
    mode: "0755"
  tags: [ oxygen, helium ]

- name: Update logs owner and permissions
  file:
    dest: /srv/app/shared/log
    owner: "{{ app_user }}"
    group: "www-data"
    mode: "0755"
    recurse: yes
  tags: [ oxygen, helium ]

- name: Install composer packages
  become: yes
  become_user: "{{ app_user }}"
  shell: composer install -d /srv/app/releases/{{ app_version }}/ --no-dev --optimize-autoloader
  tags: [ oxygen, helium ]

- name: Migrate database
  shell: php /srv/app/releases/{{ app_version }}/bin/console doctrine:schema:update --force
  args:
    executable: /bin/bash
  tags: [ oxygen, helium ]

- name: Create helium watcher service file
  template:
    src: watcher.service.j2
    dest: /etc/systemd/system/helium_watcher.service
    mode: "0750"
  notify: reload helium watcher service
  tags: [ oxygen, helium ]

- name: Enable and start helium watcher service
  systemd:
    name: helium_watcher
    state: started
    enabled: yes
  tags: [ oxygen, helium ]

- name: restart helium watcher service
  systemd:
    state: restarted
    name: helium_watcher
  tags: [ oxygen, helium ]

- name: Create helium workers service file
  template:
    src: worker.service.j2
    dest: /etc/systemd/system/helium_worker@.service
    mode: "0750"
  notify: reload helium workers service
  tags: [ oxygen, helium ]

- name: Enable and start helium workers service
  systemd:
    name: helium_worker@{{ item }}
    state: started
    enabled: yes
  with_sequence: start=1 end="{{ workers_counts }}"
  tags: [ oxygen, helium ]
