# Copyright 2022 Clivern
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Create the application user
  user:
    name: "{{ app_user }}"
    state: present
  tags: [ oxygen, helium ]

- name: Create the application group
  group:
    name: "{{ app_group }}"
    system: yes
    state: present
  tags: [ oxygen, helium ]

- name: Add the application user to the application group
  user:
    name: "{{ app_user }}"
    group: "{{ app_group }}"
    state: present
  tags: [ oxygen, helium ]

- name: Ensure releases directory exists
  file:
    path: /srv/app/releases
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'
    state: directory
  tags: [ oxygen, helium ]

- name: Ensure shared directory exists
  file:
    path: /srv/app/shared
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'
    state: directory
  tags: [ oxygen, helium ]

- name: Ensure log directory exists
  file:
    path: /srv/app/shared/log
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0775'
    state: directory
  tags: [ oxygen, helium ]

- name: Setup logrotate scripts for nginx
  template:
    src: logrotate.d.j2
    dest: /etc/logrotate.d/{{ item.name }}
    mode: "0644"
  with_items: "{{ helium_logrotate_scripts }}"
  when: helium_logrotate_scripts is defined
  tags: [ oxygen, helium ]
